-- AlterTable
ALTER TABLE `order` ADD COLUMN `cancelReason` VARCHAR(191) NULL,
    ADD COLUMN `cancelledAt` DATETIME(3) NULL,
    ADD COLUMN `cancelledByRole` VARCHAR(191) NULL,
    MODIFY `status` ENUM('PENDING', 'COOKING', 'READY', 'COMPLETED', 'CANCELLED') NOT NULL DEFAULT 'PENDING';
